spring:
  jpa:
    hibernate:
      ddl-auto: update  # or create-drop for fresh schema each run
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  profiles:
    active: dev
  springdoc:
    api-docs:
      enabled=true
    swagger-ui:
      enabled=true
